import { finish } from "./common";
import { testHistory } from "./history.test";
import { testOps } from "./ops.test";
import { testMove } from "./move.test";
import { testSym } from "./sym.test";
import { testFill } from "./fill.test";
import { testSel } from "./sel.test";
import { testPlayback } from "./playback.test";
import { testSession } from "./session.test";
import { testOrbLayout } from "./orb.test";
import { testGuide } from "./guide.test";
import { testGuideLayout } from "./guide-layout.test";
import { testGuideAnchors } from "./guide-anchors.test";
import { testRender } from "./render.test";
import { testExport } from "./export.test";
import { testBack } from "./back.test";
import { testI18n } from "./i18n.test";
import { testUiKit } from "./ui-kit.test";
import { testUiTokens } from "./ui-tokens.test";
import { testFullscreen } from "./fullscreen.test";
import { testCanvasSpace } from "./canvas-space.test";
import { testColorDrag } from "./color-drag.test";
import { testPcMode } from "./pc.test";
import { testScrub } from "./scrub.test";
import { testExpr } from "./expr.test";
import { testEffects } from "./effects.test";
import { testView } from "./view.test";
import { testSnap } from "./snap.test";

async function main(): Promise<void> {
  console.log("--- history ---");
  testHistory();
  console.log("--- ops ---");
  testOps();
  console.log("--- move ---");
  testMove();
  console.log("--- sym ---");
  testSym();
  console.log("--- fill ---");
  testFill();
  console.log("--- sel ---");
  testSel();
  console.log("--- playback ---");
  testPlayback();
  console.log("--- session ---");
  await testSession();
  console.log("--- orb layout ---");
  testOrbLayout();
  console.log("--- guide ---");
  testGuide();
  console.log("--- guide layout ---");
  testGuideLayout();
  console.log("--- guide anchors ---");
  testGuideAnchors();
  console.log("--- render ---");
  testRender();
  console.log("--- export ---");
  testExport();
  console.log("--- back ---");
  testBack();
  console.log("--- snap ---");
  testSnap();
  console.log("--- view ---");
  testView();
  console.log("--- effects ---");
  testEffects();
  console.log("--- expr ---");
  testExpr();
  console.log("--- i18n ---");
  testI18n();
  console.log("--- ui kit ---");
  testUiKit();
  console.log("--- ui tokens ---");
  testUiTokens();
  console.log("--- fullscreen ---");
  testFullscreen();
  console.log("--- canvas space ---");
  testCanvasSpace();
  console.log("--- colour drag ---");
  testColorDrag();
  console.log("--- pc mode ---");
  testPcMode();
  console.log("--- scrub ---");
  testScrub();
  finish();
}

void main().catch((e: unknown) => {
  const msg = e && (e as Error).message ? (e as Error).message : String(e);
  console.log("FATAL " + msg);
  if (e && (e as Error).stack) console.log((e as Error).stack);
  const p = (globalThis as { process?: { exitCode?: number } }).process;
  if (p) p.exitCode = 1;
});
