import { finish } from "./common";
import { testHistory } from "./history.test";
import { testOps } from "./ops.test";
import { testMove } from "./move.test";
import { testSym } from "./sym.test";
import { testFill } from "./fill.test";
import { testSel } from "./sel.test";
import { testPlayback } from "./playback.test";
import { testSession } from "./session.test";
import { testOrbLayout } from "./orb.test";
import { testGuide } from "./guide.test";
import { testGuideLayout } from "./guide-layout.test";
import { testGuideAnchors } from "./guide-anchors.test";
import { testRender } from "./render.test";
import { testExport } from "./export.test";

console.log("--- history ---");
testHistory();
console.log("--- ops ---");
testOps();
console.log("--- move ---");
testMove();
console.log("--- sym ---");
testSym();
console.log("--- fill ---");
testFill();
console.log("--- sel ---");
testSel();
console.log("--- playback ---");
testPlayback();
console.log("--- session ---");
testSession();
console.log("--- orb layout ---");
testOrbLayout();
console.log("--- guide ---");
testGuide();
console.log("--- guide layout ---");
testGuideLayout();
console.log("--- guide anchors ---");
testGuideAnchors();
console.log("--- render ---");
testRender();
console.log("--- export ---");
testExport();
finish();
